name: ci-cd-ec2

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  ECR_REPO: myapp
  IMAGE_TAG: latest

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      ecr_uri: ${{ steps.out.outputs.ecr_uri }}
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: AKIAU3OGXJCO2DLUQMPW
          aws-secret-access-key: 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
          aws-region: us-east-1


      - name: Login to ECR
        id: login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push image
        id: out
        run: |
          ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
          ECR_URI="${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}"
          echo "ecr_uri=$ECR_URI" >> "$GITHUB_OUTPUT"
          docker build -t "${ECR_URI}:${IMAGE_TAG}" .
          docker push "${ECR_URI}:${IMAGE_TAG}"

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS (OIDC)
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: AKIAU3OGXJCO2DLUQMPW
          aws-secret-access-key: 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
          aws-region: us-east-1


      - name: Deploy on EC2 via SSM
        run: |
          aws ssm send-command \
            --instance-ids i-067d09712af63e812 \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy docker image" \
            --parameters commands="AWS_REGION=us-east-1 ECR_URI=${{ needs.build_and_push.outputs.ecr_uri }} IMAGE_TAG=${IMAGE_TAG} CONTAINER_NAME=myapp PORT=8000 sudo -E /opt/app/deploy.sh"
